name: cobrowse-evidence-flow
on:
  push:
    branches:
      - master

jobs:
  gh-pages:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm --no-color install
      - run: npm --no-color run deploy -- --repo "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$INPUT_REPO.git"
